#!/bin/bash

#---------------------------------------#
#	Created by: Maik Alberto	#
#	maik.alberto@hotmail.com	#
#	    github.com/m41k		#
#---------------------------------------#

on(){
	rm -f servers 2> /dev/null
	wget www.vpngate.net/api/iphone/ -O servers 2>&1 |
	yad --progress \
	--title="CliVGate" \
	--width="200" \
	--window-icon='network-vpn' \
	--image=edit-find-symbolic \
	--text="<b>Searching servers.</b>" \
	--progress-text="Now loading..." \
	--no-buttons \
	--pulsate \
	--auto-close \
	--auto-kill

	LISTA=( `tail -n +3 servers | cut -s -d "," -f2,7 | while read LINHA; do echo "$LINHA"; done `)

	SEASE=$(yad --entry --width=200 --title="CliVGATE" \
	 --window-icon='network-vpn' \
	 --text="<b>Select a server:</b>" \
	 --entry-text \
	 ${LISTA[@]}  \
	 --button='Connect':0 )
	SERVER=( `echo $SEASE | cut -d"," -f1` )

	cat servers | grep $SERVER | cut -d"," -f15 | base64 -d > cfov 2> /dev/null

	openvpn --config cfov &
	tray
	}

off(){
	 yad --width=200 --title="CliVGATE" \
	 --window-icon='network-vpn' \
	 --text-align='center' \
	 --text="<small>Created by: github.com/m41k</small>" \
	 --buttons-layout='center' \
	 --button='Disconnect':0\
	   if [ $? -eq 0 ]; then
	      killall openvpn &
	   fi
	}

tray(){
	yad --width=200 --notification  \
        --image=network-vpn \
        --text "CliVGATE"
	off
}

ifconfig | grep tun
 if [ $? -eq 0 ]; then
  off
 fi

case $1 in
	off)off
	;;
	tray)tray
	;;
	on)on
	;;
esac
